### ISSUE TITLE
EOF Error during inference

### ISSUE THREAD

**Issue by jeb2112** [rixez/Brats21_KAIST_MRI_Lab#21]
I completed training with good results, and attempted to run the inference using this command:
```
nnUNet_predict -i D:\brats2021\nnunet_raw_data\Task005_prostate\imagesTs -o D:\brats2021\result\predictions -t 5 -m 3d_fullres -tr nnUNetTrainerV2BraTSRegions_DA4_BN_BD --save_npz
```
but am getting the following error:
```
starting prediction...
Traceback (most recent call last):
  File "\\?\C:\Users\jim\.conda\envs\pytorch_kaist\Scripts\nnUNet_predict-script.py", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_predict')())
  File "c:\users\jim\src\nnunet_kaist\nnunet\inference\predict_simple.py", line 217, in main
    predict_from_folder(model_folder_name, input_folder, output_folder, folds, save_npz, num_threads_preprocessing,
  File "c:\users\jim\src\nnunet_kaist\nnunet\inference\predict.py", line 658, in predict_from_folder
    return predict_cases(model, list_of_lists[part_id::num_parts], output_files[part_id::num_parts], folds,
  File "c:\users\jim\src\nnunet_kaist\nnunet\inference\predict.py", line 206, in predict_cases
    for preprocessed in preprocessing:
  File "c:\users\jim\src\nnunet_kaist\nnunet\inference\predict.py", line 109, in preprocess_multithreaded
    pr.start()
  File "C:\Users\jim\.conda\envs\pytorch_kaist\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\jim\.conda\envs\pytorch_kaist\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\jim\.conda\envs\pytorch_kaist\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Users\jim\.conda\envs\pytorch_kaist\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\jim\.conda\envs\pytorch_kaist\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'nnUNetTrainerV2_DA3_BN.initialize_network.<locals>.<lambda>'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\jim\.conda\envs\pytorch_kaist\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\jim\.conda\envs\pytorch_kaist\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input
[W C:\cb\pytorch_1000000000000\work\torch\csrc\CudaIPCTypes.cpp:15] Producer process has been terminated before all shared CUDA tensors released. See Note [Sharing CUDA tensors]
```
The only thing I have to go on is something about can't pickle local object, which mentions a different trainer than the one I used. Is there any hint on what is going wrong here?

**Comment by jeb2112** [comment]
I have found out this is a Windows issue, so I am closing it.
